In [1]:
# Import python modules
import os
import sys
import pandas as pd
import numpy as np

# Determine the absolute path to the src directory (one level up from notebooks)
module_path = os.path.abspath(os.path.join(os.getcwd(), "src"))
if module_path not in sys.path:
    sys.path.append(module_path)

In [2]:
# Import custom modules
import plotting
import utils

In [3]:
folder = os.path.join(os.path.dirname(os.getcwd()), "configs")

In [4]:
path = os.path.join(folder, "models", "config_37_v1_multi.yaml")
if not utils.load_model_config()["years"]:
    print("Yee")

Path_or_name:
Configuration loaded from c:\Users\tinus\OneDrive\Dokumenter\0 Master\code\master_project\configs\models\base_config.yaml
Yee

In [5]:
data_folder_path = os.path.join(
    os.getcwd(), "data", "processed", "elec_s_128_ES_PT_no_bat_limit"
)
data_folder_path

'c:\\Users\\tinus\\OneDrive\\Dokumenter\\0 Master\\code\\master_project\\data\\processed\\elec_s_128_ES_PT_no_bat_limit'

In [6]:
years = [2025, 2035, 2045]
input_data = utils.load_multi_year_csv_files_from_folder(years, data_folder_path)

In [7]:
batteries = input_data["batteries"]
branches = input_data["branches"]
capacity_factors = input_data["capacity_factors"]
generators = input_data["generators"]
generator_costs = input_data["generator_costs"]
hourly_demand = input_data["hourly_demand"]
nodes = input_data["nodes"]

In [8]:
branches["exists"] = 1
# Create a copy of the dataframe for the "new" branches
branches_new = branches.copy()
# Update the index by appending " new" to the original index
branches_new.index = branches_new.index.set_levels(
    branches_new.index.levels[1].astype(str) + " new", level="line"
)
# Set the 'exists' column to 0 for the new branches
branches_new["exists"] = 0
# Concatenate the original dataframe and the new dataframe
branches = pd.concat([branches, branches_new])
# Add a new column 'exists' to the original dataframe and set it to 1
generators["exists"] = 1
# Create a copy of the dataframe for the "new" generators
generators_new = generators.copy()
# Update the index by appending " new" to the original index
generators_new.index = generators_new.index.set_levels(
    generators_new.index.levels[1].astype(str) + " new", level="generator"
)
# Set the 'exists' column to 0 for the new generators
generators_new["exists"] = 0
# Concatenate the original dataframe and the new dataframe
generators = pd.concat([generators, generators_new])
batteries["exists"] = 0

In [9]:
branches

               bus0   bus1         p_max  capital_cost      length  \
year line
2025 88       ES1 0  ES1 3   2189.658631  23102.962586  449.297989
     89       ES1 0  ES1 6   6568.975893  11729.199350  228.105190
     90       ES1 1  ES1 2   8043.643950  16201.400425  315.078925
     91       ES1 1  ES1 4   7775.522485  22150.028030  430.765665
     92       ES1 1  ES1 5   1698.102612  19884.672096  386.709849
...             ...    ...           ...           ...         ...
2045 104 new  ES1 5  ES1 6   8758.634524  16188.029800  314.818898
     105 new  ES1 5  ES1 7  25024.670068  12467.493385  242.463263
     106 new  ES1 7  PT1 0   3172.770669  13131.503581  255.376691
     107 new  ES1 7  PT1 1   1698.102612  22061.025373  429.034774
     219 new  PT1 0  PT1 1  11707.970639  14480.882016  281.618911

              loss_factor  exists
year line
2025 88          0.017250       1
     89          0.008758       1
     90          0.012097       1
     91          0.016539       1
     92          0.014847       1
...                   ...     ...
2045 104 new     0.012087       0
     105 new     0.009309       0
     106 new     0.009805       0
     107 new     0.016472       0
     219 new     0.010812       0

[114 rows x 7 columns]

In [10]:
hourly_demand

                 ES1 0         ES1 1        ES1 2         ES1 3        ES1 4  \
year hour
2025 0     1540.497187   3541.798151  1849.109695   2953.965919  2331.873044
     1     1433.747317   3296.366678  1720.974297   2749.268707  2170.284209
     2     1335.043919   3069.435065  1602.497346   2560.000934  2020.875437
     3     1273.019026   2926.831980  1528.046816   2441.065682  1926.987452
     4     1250.287740   2874.569876  1500.761703   2397.477519  1892.578775
...                ...           ...          ...           ...          ...
2045 8755  6142.878375  14123.255438  7373.499966  11779.218761  9298.564525
     8756  5776.361546  13280.586826  6933.557702  11076.407857  8743.762659
     8757  5320.528871  12232.569770  6386.406674  10202.330190  8053.762096
     8758  5093.819505  11711.336222  6114.279928   9767.605772  7710.588823
     8759  4868.920594  11194.265141  5844.326332   9336.352978  7370.156065

                  ES1 5        ES1 6        ES1 7         ES1 8        PT1 0  \
year hour
2025 0      3518.575677  2092.739520  1871.996365   2787.386472  2275.245735
     1      3274.753423  1947.721616  1742.275019   2594.232504  2182.798908
     2      3049.309730  1813.634710  1622.331663   2415.637880  2041.494173
     3      2907.641648  1729.374936  1546.959650   2303.409601  1916.954406
     4      2855.722211  1698.494867  1519.336825   2262.279453  1845.104541
...                 ...          ...          ...           ...          ...
2045 8755  14030.653624  8344.996958  7464.762733  11114.967444  9317.490533
     8756  13193.510129  7847.090011  7019.375245  10451.789310  8433.737190
     8757  12152.364597  7227.848988  6465.452059   9627.002453  7965.276068
     8758  11634.548616  6919.868127  6189.957164   9216.792927  7746.852478
     8759  11120.867810  6614.346739  5916.662317   8809.859253  7384.729156

                  PT1 1
year hour
2025 0      2474.754265
     1      2374.201092
     2      2220.505827
     3      2085.045594
     4      2006.895459
...                 ...
2045 8755  10134.509467
     8756   9173.262810
     8757   8663.723932
     8758   8426.147522
     8759   8032.270844

[26280 rows x 11 columns]

In [11]:
nodes.index.names

FrozenList(['bus'])

In [12]:
"year" in batteries.index.names

True

In [13]:
generators

                             bus     carrier        p_nom  marginal_cost  \
year generator
2025 ES1 0 CCGT            ES1 0        CCGT  3425.300000      38.855172
     ES1 0 coal            ES1 0        coal  1068.524933      28.196970
     ES1 0 offwind-ac      ES1 0  offwind-ac   212.585059       0.015000
     ES1 0 onwind          ES1 0      onwind  1487.775552       0.015000
     ES1 0 solar           ES1 0       solar  1103.286390       0.010000
...                          ...         ...          ...            ...
2045 PT1 1 CCGT new        PT1 1        CCGT  3004.000000      38.892841
     PT1 1 offwind-ac new  PT1 1  offwind-ac  3404.177205       0.015000
     PT1 1 onwind new      PT1 1      onwind  3672.827789       0.015000
     PT1 1 ror new         PT1 1         ror   269.600000       0.000000
     PT1 1 solar new       PT1 1       solar   648.073599       0.010000

                            capital_cost  co2_emissions    color  \
year generator
2025 ES1 0 CCGT             99027.729293           0.20  #b20101
     ES1 0 coal            349976.553630           0.34  #707070
     ES1 0 offwind-ac      183919.033054           0.00  #6895dd
     ES1 0 onwind           96085.888020           0.00  #235ebc
     ES1 0 solar            35602.071244           0.00  #f9d002
...                                  ...            ...      ...
2045 PT1 1 CCGT new         99027.729293           0.20  #b20101
     PT1 1 offwind-ac new  185562.894661           0.00  #6895dd
     PT1 1 onwind new       96085.888020           0.00  #235ebc
     PT1 1 ror new         299140.224929           0.00  #4adbc8
     PT1 1 solar new        35602.071244           0.00  #f9d002

                                    nice_name  exists
year generator
2025 ES1 0 CCGT            Combined-Cycle Gas       1
     ES1 0 coal                          Coal       1
     ES1 0 offwind-ac      Offshore Wind (AC)       1
     ES1 0 onwind                Onshore Wind       1
     ES1 0 solar                        Solar       1
...                                       ...     ...
2045 PT1 1 CCGT new        Combined-Cycle Gas       0
     PT1 1 offwind-ac new  Offshore Wind (AC)       0
     PT1 1 onwind new            Onshore Wind       0
     PT1 1 ror new               Run of River       0
     PT1 1 solar new                    Solar       0

[306 rows x 9 columns]

In [14]:
hourly_demand.loc[(2025, 0), "ES1 0"]

1540.4971869334968

In [15]:
generators

                             bus     carrier        p_nom  marginal_cost  \
year generator
2025 ES1 0 CCGT            ES1 0        CCGT  3425.300000      38.855172
     ES1 0 coal            ES1 0        coal  1068.524933      28.196970
     ES1 0 offwind-ac      ES1 0  offwind-ac   212.585059       0.015000
     ES1 0 onwind          ES1 0      onwind  1487.775552       0.015000
     ES1 0 solar           ES1 0       solar  1103.286390       0.010000
...                          ...         ...          ...            ...
2045 PT1 1 CCGT new        PT1 1        CCGT  3004.000000      38.892841
     PT1 1 offwind-ac new  PT1 1  offwind-ac  3404.177205       0.015000
     PT1 1 onwind new      PT1 1      onwind  3672.827789       0.015000
     PT1 1 ror new         PT1 1         ror   269.600000       0.000000
     PT1 1 solar new       PT1 1       solar   648.073599       0.010000

                            capital_cost  co2_emissions    color  \
year generator
2025 ES1 0 CCGT             99027.729293           0.20  #b20101
     ES1 0 coal            349976.553630           0.34  #707070
     ES1 0 offwind-ac      183919.033054           0.00  #6895dd
     ES1 0 onwind           96085.888020           0.00  #235ebc
     ES1 0 solar            35602.071244           0.00  #f9d002
...                                  ...            ...      ...
2045 PT1 1 CCGT new         99027.729293           0.20  #b20101
     PT1 1 offwind-ac new  185562.894661           0.00  #6895dd
     PT1 1 onwind new       96085.888020           0.00  #235ebc
     PT1 1 ror new         299140.224929           0.00  #4adbc8
     PT1 1 solar new        35602.071244           0.00  #f9d002

                                    nice_name  exists
year generator
2025 ES1 0 CCGT            Combined-Cycle Gas       1
     ES1 0 coal                          Coal       1
     ES1 0 offwind-ac      Offshore Wind (AC)       1
     ES1 0 onwind                Onshore Wind       1
     ES1 0 solar                        Solar       1
...                                       ...     ...
2045 PT1 1 CCGT new        Combined-Cycle Gas       0
     PT1 1 offwind-ac new  Offshore Wind (AC)       0
     PT1 1 onwind new            Onshore Wind       0
     PT1 1 ror new               Run of River       0
     PT1 1 solar new                    Solar       0

[306 rows x 9 columns]

In [16]:
from models import get_model
from utils import load_model_config

model_config = load_model_config("37_v1_multi")

values = get_model(model_config)

Path_or_name: 37_v1_multi
Configuration loaded from c:\Users\tinus\OneDrive\Dokumenter\0 Master\code\master_project\configs\models\config_37_v1_multi.yaml
Set parameter Username
Academic license - for non-commercial use only - expires 2025-09-27

c:\Users\tinus\OneDrive\Dokumenter\0 Master\code\master_project\src\models.py:50: PerformanceWarning: indexing past lexsort depth may impact performance.
  branches = branches.loc[y0,]
c:\Users\tinus\OneDrive\Dokumenter\0 Master\code\master_project\src\models.py:51: PerformanceWarning: indexing past lexsort depth may impact performance.
  generators = generators.loc[y0,]

Set parameter MIPGap to value 0.01
Set parameter BarConvTol to value 0.01
Model built in 286.21843910217285 seconds.
Gurobi Optimizer version 11.0.3 build v11.0.3rc0 (win64 - Windows 11+.0 (26100.2))

CPU model: AMD Ryzen 7 5800H with Radeon Graphics, instruction set [SSE2|AVX|AVX2]
Thread count: 8 physical cores, 16 logical processors, using up to 16 threads

Optimize a model with 1629442 rows, 1419204 columns and 4256197 nonzeros
Model fingerprint: 0xe2a584c2
Coefficient statistics:
  Matrix range     [8e-07, 1e+00]
  Objective range  [9e-04, 1e+05]
  Bounds range     [0e+00, 0e+00]
  RHS range        [6e-03, 1e+05]
Presolve removed 780753 rows and 466586 columns
Presolve time: 5.12s
Presolved: 848689 rows, 952618 columns, 2987618 nonzeros

Concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Ordering time: 0.96s

Barrier statistics:
 Dense cols : 46
 Free vars  : 26280
 AA' NZ     : 2.865e+06
 Factor NZ  : 1.290e+07 (roughly 800 MB of memory)
 Factor Ops : 2.689e+08 (less than 1 second per iteration)
 Threads    : 6

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0   3.11793671e+13 -1.30804326e+15  1.18e+06 6.11e+02  4.09e+10     9s
   1   2.85137149e+13 -1.27098940e+15  1.07e+06 5.06e+04  2.98e+10    10s
   2   2.44352575e+13 -1.23653420e+15  9.00e+05 3.46e+04  2.42e+10    11s
   3   2.31075989e+13 -1.13707215e+15  8.49e+05 1.49e+04  2.02e+10    13s
   4   1.95825229e+13 -1.03764424e+15  7.08e+05 8.05e+04  1.61e+10    14s
   5   1.61413498e+13 -9.35896365e+14  5.71e+05 1.32e+05  1.27e+10    15s
   6   1.23591470e+13 -8.41650449e+14  4.19e+05 1.55e+05  9.23e+09    16s
   7   1.02909682e+13 -7.59279228e+14  3.45e+05 1.50e+05  7.33e+09    17s
   8   6.02477322e+12 -7.18441046e+14  1.95e+05 1.46e+05  4.26e+09    18s
   9   3.78408683e+12 -6.60400838e+14  1.18e+05 6.92e+04  2.63e+09    19s
  10   3.10861713e+12 -6.27322739e+14  9.43e+04 7.77e+04  2.14e+09    20s
  11   2.20973981e+12 -5.56563001e+14  6.39e+04 7.58e+04  1.47e+09    21s
  12   1.38942361e+12 -4.56271069e+14  3.70e+04 4.43e+04  8.72e+08    21s
  13   9.39096305e+11 -3.53375468e+14  2.27e+04 2.36e+04  5.35e+08    22s
  14   5.99954722e+11 -2.61594565e+14  1.20e+04 6.78e+03  2.98e+08    23s
  15   4.40863680e+11 -1.82357266e+14  7.15e+03 8.55e+02  1.76e+08    24s
  16   3.35875662e+11 -1.17256040e+14  3.85e+03 3.36e+03  9.47e+07    24s
  17   3.47076825e+11 -1.17197412e+14  3.84e+03 3.81e+04  9.46e+07    25s
  18   3.75666301e+11 -1.16570228e+14  3.68e+03 4.18e+04  9.27e+07    26s
  19   3.45153269e+11 -1.16555726e+14  3.68e+03 3.95e+04  9.27e+07    27s
  20   3.45153269e+11 -1.16555726e+14  3.68e+03 3.95e+04  9.27e+07    29s
  21   3.46506067e+11 -1.15343922e+14  3.61e+03 4.08e+04  9.12e+07    30s
  22   2.41027187e+11 -3.92635669e+13  2.32e+02 4.35e+03  1.94e+07    33s
  23   2.38563905e+11 -3.92610434e+13  2.32e+02 5.99e+03  1.95e+07    35s
  24   2.36218430e+11 -3.92583767e+13  2.32e+02 9.04e+03  1.95e+07    37s
  25   2.34925065e+11 -3.92551756e+13  2.32e+02 2.47e+04  1.95e+07    38s
  26   2.34336546e+11 -3.92538557e+13  2.32e+02 4.52e+04  1.95e+07    40s
  27   3.29316984e+11 -3.36300833e+13  1.67e+02 3.57e+04  1.68e+07    43s
  28   2.64432645e+11 -1.63405542e+12  5.49e-06 2.56e+03  8.64e+05    45s
  29   2.62954247e+11 -1.63247320e+12  5.49e-06 1.97e+04  8.71e+05    46s
  30   1.43174865e+11 -4.78988029e+11  8.04e-08 1.82e+03  2.76e+05    49s
  31   1.43174865e+11 -4.78988029e+11  8.04e-08 1.82e+03  2.76e+05    50s
  32   1.34293535e+14 -1.30811849e+16  5.10e+06 6.11e+02  1.73e+12    53s
  33   1.18826918e+14 -1.97411764e+16  4.45e+06 4.92e+05  1.60e+12    54s
  34   1.05441971e+14 -1.93452414e+16  3.89e+06 1.47e+05  1.20e+12    55s
  35   8.36792047e+13 -1.86070390e+16  3.03e+06 7.86e+04  9.06e+11    57s
  36   6.59382483e+13 -1.79659424e+16  2.31e+06 4.23e+05  6.84e+11    58s
  37   5.28616429e+13 -1.71315482e+16  1.79e+06 1.70e+05  5.31e+11    59s
  38   4.79924712e+13 -1.62935593e+16  1.61e+06 2.56e+05  4.69e+11    60s
  39   3.61454671e+13 -1.58910722e+16  1.19e+06 4.22e+05  3.49e+11    61s
  40   2.19786817e+13 -1.53621857e+16  7.08e+05 2.43e+05  2.10e+11    62s
  41   1.73166253e+13 -1.48354601e+16  5.47e+05 6.47e+05  1.63e+11    63s
  42   1.40997316e+13 -1.41495979e+16  4.38e+05 7.64e+05  1.30e+11    63s
  43   1.15074075e+13 -1.34523825e+16  3.51e+05 6.87e+05  1.04e+11    64s
  44   8.72481144e+12 -1.22189766e+16  2.61e+05 4.77e+05  7.70e+10    65s
  45   6.42243090e+12 -1.13218702e+16  1.88e+05 3.24e+05  5.57e+10    66s
  46   5.18375285e+12 -1.05597174e+16  1.49e+05 2.35e+05  4.42e+10    67s
  47   3.89427799e+12 -9.45776659e+15  1.09e+05 1.39e+05  3.22e+10    67s
  48   2.78813922e+12 -8.41709966e+15  7.43e+04 7.48e+04  2.24e+10    68s
  49   1.76696364e+12 -7.09542727e+15  4.22e+04 3.23e+04  1.33e+10    69s
  50   1.24003275e+12 -5.75403123e+15  2.53e+04 8.69e+03  8.26e+09    70s
  51   9.95282601e+11 -4.28499597e+15  1.70e+04 1.34e+04  5.39e+09    70s
  52   9.00325646e+11 -4.13871736e+15  1.18e+04 3.02e+05  4.24e+09    71s
  53   8.47931352e+11 -4.13825953e+15  1.18e+04 1.14e+05  4.24e+09    72s
  54   8.50250218e+11 -4.13558070e+15  1.18e+04 1.55e+05  4.24e+09    73s
  55   8.51580886e+11 -4.13303287e+15  1.18e+04 1.69e+05  4.24e+09    75s
  56   8.52572058e+11 -4.13130129e+15  1.18e+04 1.76e+05  4.23e+09    76s
  57   8.53446718e+11 -4.12923152e+15  1.18e+04 1.83e+05  4.23e+09    78s
  58   8.54939227e+11 -4.12789995e+15  1.18e+04 1.91e+05  4.23e+09    79s
  59   8.59859686e+11 -4.12618745e+15  1.18e+04 2.02e+05  4.22e+09    80s
  60   8.66843724e+11 -4.12341618e+15  1.17e+04 2.21e+05  4.22e+09    82s
  61   8.87882906e+11 -4.11972324e+15  1.17e+04 2.45e+05  4.20e+09    83s
  62   8.63485828e+11 -4.11930342e+15  1.17e+04 1.06e+05  4.21e+09    85s

Barrier performed 62 iterations in 85.01 seconds (37.09 work units)
Numerical trouble encountered

Model may be infeasible or unbounded.  Consider using the
homogeneous algorithm (through parameter 'BarHomogeneous')

Waiting for other threads to finish...         270s
Waiting for other threads to finish...         455s

Solved with dual simplex
Iteration    Objective       Primal Inf.    Dual Inf.      Time
  682957    1.0698862e+10   0.000000e+00   0.000000e+00    540s

Solved in 682957 iterations and 539.58 seconds (492.88 work units)
Optimal objective  1.069886214e+10

ValueError: not enough values to unpack (expected 5, got 3)

In [ ]:
# generation_data = [(y, t, i, g[i, y, t].X) for i in G for y in Y for t in T]
generation_data

[(2025, 0, 'ES1 0 CCGT', 0.0),
 (2025, 1, 'ES1 0 CCGT', 0.0),
 (2025, 2, 'ES1 0 CCGT', 0.0),
 (2025, 3, 'ES1 0 CCGT', 0.0),
 (2025, 4, 'ES1 0 CCGT', 0.0),
 (2025, 5, 'ES1 0 CCGT', 0.0),
 (2025, 6, 'ES1 0 CCGT', 0.0),
 (2025, 7, 'ES1 0 CCGT', 0.0),
 (2025, 8, 'ES1 0 CCGT', 0.0),
 (2025, 9, 'ES1 0 CCGT', 0.0),
 (2025, 10, 'ES1 0 CCGT', 0.0),
 (2025, 11, 'ES1 0 CCGT', 0.0),
 (2025, 12, 'ES1 0 CCGT', 0.0),
 (2025, 13, 'ES1 0 CCGT', 0.0),
 (2025, 14, 'ES1 0 CCGT', 0.0),
 (2025, 15, 'ES1 0 CCGT', 0.0),
 (2025, 16, 'ES1 0 CCGT', 0.0),
 (2025, 17, 'ES1 0 CCGT', 3181.795677133754),
 (2025, 18, 'ES1 0 CCGT', 4892.4817871971845),
 (2025, 19, 'ES1 0 CCGT', 6260.750036544544),
 (2025, 20, 'ES1 0 CCGT', 6842.360302620502),
 (2025, 21, 'ES1 0 CCGT', 1506.2001785665207),
 (2025, 22, 'ES1 0 CCGT', 5919.685152732546),
 (2025, 23, 'ES1 0 CCGT', 1193.1179713358988),
 (2025, 24, 'ES1 0 CCGT', 0.0),
 (2025, 25, 'ES1 0 CCGT', 0.0),
 (2025, 26, 'ES1 0 CCGT', 0.0),
 (2025, 27, 'ES1 0 CCGT', 0.0),
 (2025, 28, 'ES1 0 CCGT', 0.0),
 (2025, 29, 'ES1 0 CCGT', 0.0),
 (2025, 30, 'ES1 0 CCGT', 0.0),
 (2025, 31, 'ES1 0 CCGT', 2595.079414132935),
 (2025, 32, 'ES1 0 CCGT', 3730.0926452332715),
 (2025, 33, 'ES1 0 CCGT', 0.0),
 (2025, 34, 'ES1 0 CCGT', 0.0),
 (2025, 35, 'ES1 0 CCGT', 0.0),
 (2025, 36, 'ES1 0 CCGT', 0.0),
 (2025, 37, 'ES1 0 CCGT', 0.0),
 (2025, 38, 'ES1 0 CCGT', 0.0),
 (2025, 39, 'ES1 0 CCGT', 0.0),
 (2025, 40, 'ES1 0 CCGT', 620.7484852715475),
 (2025, 41, 'ES1 0 CCGT', 5717.140672412835),
 (2025, 42, 'ES1 0 CCGT', 4901.888587696467),
 (2025, 43, 'ES1 0 CCGT', 3905.5482684523304),
 (2025, 44, 'ES1 0 CCGT', 3120.7108011990617),
 (2025, 45, 'ES1 0 CCGT', 1002.3613113882575),
 (2025, 46, 'ES1 0 CCGT', 705.6427195201122),
 (2025, 47, 'ES1 0 CCGT', 0.0),
 (2025, 48, 'ES1 0 CCGT', 0.0),
 (2025, 49, 'ES1 0 CCGT', 0.0),
 (2025, 50, 'ES1 0 CCGT', 0.0),
 (2025, 51, 'ES1 0 CCGT', 0.0),
 (2025, 52, 'ES1 0 CCGT', 0.0),
 (2025, 53, 'ES1 0 CCGT', 0.0),
 (2025, 54, 'ES1 0 CCGT', 0.0),
 (2025, 55, 'ES1 0 CCGT', 1932.9335089562874),
 (2025, 56, 'ES1 0 CCGT', 3481.499304806389),
 (2025, 57, 'ES1 0 CCGT', 0.0),
 (2025, 58, 'ES1 0 CCGT', 0.0),
 (2025, 59, 'ES1 0 CCGT', 0.0),
 (2025, 60, 'ES1 0 CCGT', 0.0),
 (2025, 61, 'ES1 0 CCGT', 0.0),
 (2025, 62, 'ES1 0 CCGT', 0.0),
 (2025, 63, 'ES1 0 CCGT', 0.0),
 (2025, 64, 'ES1 0 CCGT', 10150.778546548556),
 (2025, 65, 'ES1 0 CCGT', 16952.000760373907),
 (2025, 66, 'ES1 0 CCGT', 16956.87105700151),
 (2025, 67, 'ES1 0 CCGT', 16375.509645314953),
 (2025, 68, 'ES1 0 CCGT', 15504.137814798356),
 (2025, 69, 'ES1 0 CCGT', 13191.556746877335),
 (2025, 70, 'ES1 0 CCGT', 9173.461793485467),
 (2025, 71, 'ES1 0 CCGT', 6362.703413670518),
 (2025, 72, 'ES1 0 CCGT', 3416.7882337744213),
 (2025, 73, 'ES1 0 CCGT', 1509.778808189527),
 (2025, 74, 'ES1 0 CCGT', 477.25955490286105),
 (2025, 75, 'ES1 0 CCGT', 0.0),
 (2025, 76, 'ES1 0 CCGT', 62.3758972836622),
 (2025, 77, 'ES1 0 CCGT', 1970.3767431544693),
 (2025, 78, 'ES1 0 CCGT', 5455.65423045362),
 (2025, 79, 'ES1 0 CCGT', 9049.935827947742),
 (2025, 80, 'ES1 0 CCGT', 9597.13429451798),
 (2025, 81, 'ES1 0 CCGT', 0.0),
 (2025, 82, 'ES1 0 CCGT', 0.0),
 (2025, 83, 'ES1 0 CCGT', 0.0),
 (2025, 84, 'ES1 0 CCGT', 0.0),
 (2025, 85, 'ES1 0 CCGT', 0.0),
 (2025, 86, 'ES1 0 CCGT', 0.0),
 (2025, 87, 'ES1 0 CCGT', 1704.9923831433443),
 (2025, 88, 'ES1 0 CCGT', 11935.687872138591),
 (2025, 89, 'ES1 0 CCGT', 18828.843353707703),
 (2025, 90, 'ES1 0 CCGT', 18564.609014224716),
 (2025, 91, 'ES1 0 CCGT', 17727.17521558772),
 (2025, 92, 'ES1 0 CCGT', 16921.16522942731),
 (2025, 93, 'ES1 0 CCGT', 15117.213886156696),
 (2025, 94, 'ES1 0 CCGT', 12638.473054649818),
 (2025, 95, 'ES1 0 CCGT', 10739.246055713638),
 (2025, 96, 'ES1 0 CCGT', 8758.053821062373),
 (2025, 97, 'ES1 0 CCGT', 7115.4822601866845),
 (2025, 98, 'ES1 0 CCGT', 6567.381868101046),
 (2025, 99, 'ES1 0 CCGT', 6504.606618141178),
 (2025, 100, 'ES1 0 CCGT', 6543.288710026517),
 (2025, 101, 'ES1 0 CCGT', 7018.633084743627),
 (2025, 102, 'ES1 0 CCGT', 7975.223649896411),
 (2025, 103, 'ES1 0 CCGT', 8972.057956100023),
 (2025, 104, 'ES1 0 CCGT', 9223.807306308601),
 (2025, 105, 'ES1 0 CCGT', 0.0),
 (2025, 106, 'ES1 0 CCGT', 0.0),
 (2025, 107, 'ES1 0 CCGT', 0.0),
 (2025, 108, 'ES1 0 CCGT', 0.0),
 (2025, 109, 'ES1 0 CCGT', 0.0),
 (2025, 110, 'ES1 0 CCGT', 0.0),
 (2025, 111, 'ES1 0 CCGT', 517.4789735394725),
 (2025, 112, 'ES1 0 CCGT', 8529.384136044655),
 (2025, 113, 'ES1 0 CCGT', 14552.479963248798),
 (2025, 114, 'ES1 0 CCGT', 14651.054612792239),
 (2025, 115, 'ES1 0 CCGT', 14973.914305383303),
 (2025, 116, 'ES1 0 CCGT', 15338.302674674776),
 (2025, 117, 'ES1 0 CCGT', 14914.996306557532),
 (2025, 118, 'ES1 0 CCGT', 14230.046156900036),
 (2025, 119, 'ES1 0 CCGT', 11733.801046998726),
 (2025, 120, 'ES1 0 CCGT', 9120.15272058808),
 (2025, 121, 'ES1 0 CCGT', 6868.442291946048),
 (2025, 122, 'ES1 0 CCGT', 5920.770156789322),
 (2025, 123, 'ES1 0 CCGT', 5437.694377449874),
 (2025, 124, 'ES1 0 CCGT', 5816.9685610534625),
 (2025, 125, 'ES1 0 CCGT', 6410.90008313499),
 (2025, 126, 'ES1 0 CCGT', 7352.2725772934145),
 (2025, 127, 'ES1 0 CCGT', 8089.511181787777),
 (2025, 128, 'ES1 0 CCGT', 7622.124140052871),
 (2025, 129, 'ES1 0 CCGT', 0.0),
 (2025, 130, 'ES1 0 CCGT', 0.0),
 (2025, 131, 'ES1 0 CCGT', 0.0),
 (2025, 132, 'ES1 0 CCGT', 0.0),
 (2025, 133, 'ES1 0 CCGT', 0.0),
 (2025, 134, 'ES1 0 CCGT', 0.0),
 (2025, 135, 'ES1 0 CCGT', 1033.9578396357902),
 (2025, 136, 'ES1 0 CCGT', 10589.598645676946),
 (2025, 137, 'ES1 0 CCGT', 18474.47322189075),
 (2025, 138, 'ES1 0 CCGT', 19398.175957040858),
 (2025, 139, 'ES1 0 CCGT', 20288.88103645096),
 (2025, 140, 'ES1 0 CCGT', 20955.29379325529),
 (2025, 141, 'ES1 0 CCGT', 20536.671675013033),
 (2025, 142, 'ES1 0 CCGT', 17901.82518875171),
 (2025, 143, 'ES1 0 CCGT', 14545.02665691542),
 (2025, 144, 'ES1 0 CCGT', 11769.707380183452),
 (2025, 145, 'ES1 0 CCGT', 9761.762976121006),
 (2025, 146, 'ES1 0 CCGT', 9000.909669670573),
 (2025, 147, 'ES1 0 CCGT', 8857.079614769558),
 (2025, 148, 'ES1 0 CCGT', 9258.06226713475),
 (2025, 149, 'ES1 0 CCGT', 11089.682151974863),
 (2025, 150, 'ES1 0 CCGT', 14061.482343557294),
 (2025, 151, 'ES1 0 CCGT', 16294.775776713119),
 (2025, 152, 'ES1 0 CCGT', 16264.056613607978),
 (2025, 153, 'ES1 0 CCGT', 7637.860605472485),
 (2025, 154, 'ES1 0 CCGT', 4430.466157162776),
 (2025, 155, 'ES1 0 CCGT', 2949.483760979322),
 (2025, 156, 'ES1 0 CCGT', 2313.058088704069),
 (2025, 157, 'ES1 0 CCGT', 2770.0834161204193),
 (2025, 158, 'ES1 0 CCGT', 4794.193867866159),
 (2025, 159, 'ES1 0 CCGT', 8959.080541129753),
 (2025, 160, 'ES1 0 CCGT', 16684.38380590607),
 (2025, 161, 'ES1 0 CCGT', 22748.02774930681),
 (2025, 162, 'ES1 0 CCGT', 23949.038691504775),
 (2025, 163, 'ES1 0 CCGT', 24494.13432966701),
 (2025, 164, 'ES1 0 CCGT', 24078.897085890407),
 (2025, 165, 'ES1 0 CCGT', 21578.41545022907),
 (2025, 166, 'ES1 0 CCGT', 17456.369235581406),
 (2025, 167, 'ES1 0 CCGT', 13925.82303375443),
 (2025, 168, 'ES1 0 CCGT', 10815.148092546435),
 (2025, 169, 'ES1 0 CCGT', 8937.131137809913),
 (2025, 170, 'ES1 0 CCGT', 7879.755042335471),
 (2025, 171, 'ES1 0 CCGT', 7709.593947553168),
 (2025, 172, 'ES1 0 CCGT', 8281.398851055506),
 (2025, 173, 'ES1 0 CCGT', 11052.421446518078),
 (2025, 174, 'ES1 0 CCGT', 16326.535094355633),
 (2025, 175, 'ES1 0 CCGT', 20878.331393586803),
 (2025, 176, 'ES1 0 CCGT', 20565.647587689164),
 (2025, 177, 'ES1 0 CCGT', 13925.768481686431),
 (2025, 178, 'ES1 0 CCGT', 11273.12477295351),
 (2025, 179, 'ES1 0 CCGT', 8624.336386795194),
 (2025, 180, 'ES1 0 CCGT', 6767.1686407376565),
 (2025, 181, 'ES1 0 CCGT', 5971.842126486117),
 (2025, 182, 'ES1 0 CCGT', 8152.808378032514),
 (2025, 183, 'ES1 0 CCGT', 12251.44337175801),
 (2025, 184, 'ES1 0 CCGT', 19492.147111053266),
 (2025, 185, 'ES1 0 CCGT', 25112.92446493802),
 (2025, 186, 'ES1 0 CCGT', 25645.630389424376),
 (2025, 187, 'ES1 0 CCGT', 25290.7399303151),
 (2025, 188, 'ES1 0 CCGT', 24066.25880331859),
 (2025, 189, 'ES1 0 CCGT', 20994.03667898332),
 (2025, 190, 'ES1 0 CCGT', 18008.25645793343),
 (2025, 191, 'ES1 0 CCGT', 13876.846821948759),
 (2025, 192, 'ES1 0 CCGT', 10561.587129822348),
 (2025, 193, 'ES1 0 CCGT', 8405.726334866486),
 (2025, 194, 'ES1 0 CCGT', 7117.202475311202),
 (2025, 195, 'ES1 0 CCGT', 6255.544622602672),
 (2025, 196, 'ES1 0 CCGT', 6558.4772570137075),
 (2025, 197, 'ES1 0 CCGT', 8941.385527866498),
 (2025, 198, 'ES1 0 CCGT', 14111.897267542508),
 (2025, 199, 'ES1 0 CCGT', 18418.3186278399),
 (2025, 200, 'ES1 0 CCGT', 18345.020414463095),
 (2025, 201, 'ES1 0 CCGT', 12980.403690843887),
 (2025, 202, 'ES1 0 CCGT', 11191.649522405518),
 (2025, 203, 'ES1 0 CCGT', 8170.496135793253),
 (2025, 204, 'ES1 0 CCGT', 5378.970494638522),
 (2025, 205, 'ES1 0 CCGT', 3247.0305161569067),
 (2025, 206, 'ES1 0 CCGT', 4951.707452713638),
 (2025, 207, 'ES1 0 CCGT', 5982.6507754876275),
 (2025, 208, 'ES1 0 CCGT', 10718.896966091466),
 (2025, 209, 'ES1 0 CCGT', 14629.272285402114),
 (2025, 210, 'ES1 0 CCGT', 14774.615894342503),
 (2025, 211, 'ES1 0 CCGT', 13825.912342768203),
 (2025, 212, 'ES1 0 CCGT', 12254.127973195169),
 (2025, 213, 'ES1 0 CCGT', 8591.77930155693),
 (2025, 214, 'ES1 0 CCGT', 3854.7077704574476),
 (2025, 215, 'ES1 0 CCGT', 0.0),
 (2025, 216, 'ES1 0 CCGT', 0.0),
 (2025, 217, 'ES1 0 CCGT', 0.0),
 (2025, 218, 'ES1 0 CCGT', 0.0),
 (2025, 219, 'ES1 0 CCGT', 0.0),
 (2025, 220, 'ES1 0 CCGT', 0.0),
 (2025, 221, 'ES1 0 CCGT', 0.0),
 (2025, 222, 'ES1 0 CCGT', 3176.552718046535),
 (2025, 223, 'ES1 0 CCGT', 8803.784580230898),
 (2025, 224, 'ES1 0 CCGT', 9385.228786412434),
 (2025, 225, 'ES1 0 CCGT', 5103.476761972121),
 (2025, 226, 'ES1 0 CCGT', 2130.4713637680447),
 (2025, 227, 'ES1 0 CCGT', 0.0),
 (2025, 228, 'ES1 0 CCGT', 0.0),
 (2025, 229, 'ES1 0 CCGT', 0.0),
 (2025, 230, 'ES1 0 CCGT', 0.0),
 (2025, 231, 'ES1 0 CCGT', 3404.6661700234968),
 (2025, 232, 'ES1 0 CCGT', 12280.732461514392),
 (2025, 233, 'ES1 0 CCGT', 18967.60878450316),
 (2025, 234, 'ES1 0 CCGT', 19981.94113797146),
 (2025, 235, 'ES1 0 CCGT', 19737.62827453295),
 (2025, 236, 'ES1 0 CCGT', 18692.136398639115),
 (2025, 237, 'ES1 0 CCGT', 16297.430372168747),
 (2025, 238, 'ES1 0 CCGT', 13480.486771358634),
 (2025, 239, 'ES1 0 CCGT', 10079.463500650065),
 (2025, 240, 'ES1 0 CCGT', 7766.757941366057),
 (2025, 241, 'ES1 0 CCGT', 6417.961992092494),
 (2025, 242, 'ES1 0 CCGT', 5773.573913561866),
 (2025, 243, 'ES1 0 CCGT', 6027.08300287738),
 (2025, 244, 'ES1 0 CCGT', 6795.120600264119),
 (2025, 245, 'ES1 0 CCGT', 9828.429426639115),
 (2025, 246, 'ES1 0 CCGT', 15360.688011607335),
 (2025, 247, 'ES1 0 CCGT', 20281.94058871138),
 (2025, 248, 'ES1 0 CCGT', 20491.916730411045),
 (2025, 249, 'ES1 0 CCGT', 13571.605715879721),
 (2025, 250, 'ES1 0 CCGT', 10040.607962897024),
 (2025, 251, 'ES1 0 CCGT', 6660.6837497337065),
 (2025, 252, 'ES1 0 CCGT', 4037.711571845832),
 (2025, 253, 'ES1 0 CCGT', 1722.040979486952),
 (2025, 254, 'ES1 0 CCGT', 2112.590785296187),
 (2025, 255, 'ES1 0 CCGT', 5543.359579280277),
 (2025, 256, 'ES1 0 CCGT', 13149.098107851662),
 (2025, 257, 'ES1 0 CCGT', 18449.889733870612),
 (2025, 258, 'ES1 0 CCGT', 18475.95262164892),
 (2025, 259, 'ES1 0 CCGT', 17597.933127247667),
 (2025, 260, 'ES1 0 CCGT', 16203.207738053477),
 (2025, 261, 'ES1 0 CCGT', 13967.76697584489),
 (2025, 262, 'ES1 0 CCGT', 11268.513914504587),
 (2025, 263, 'ES1 0 CCGT', 8718.807359106999),
 (2025, 264, 'ES1 0 CCGT', 5385.332176607421),
 (2025, 265, 'ES1 0 CCGT', 2511.3519831939066),
 (2025, 266, 'ES1 0 CCGT', 731.884797786287),
 (2025, 267, 'ES1 0 CCGT', 0.0),
 (2025, 268, 'ES1 0 CCGT', 0.0),
 (2025, 269, 'ES1 0 CCGT', 0.0),
 (2025, 270, 'ES1 0 CCGT', 1241.2553080498492),
 (2025, 271, 'ES1 0 CCGT', 2932.900502225886),
 (2025, 272, 'ES1 0 CCGT', 3572.1905311482096),
 (2025, 273, 'ES1 0 CCGT', 0.0),
 (2025, 274, 'ES1 0 CCGT', 0.0),
 (2025, 275, 'ES1 0 CCGT', 0.0),
 (2025, 276, 'ES1 0 CCGT', 0.0),
 (2025, 277, 'ES1 0 CCGT', 0.0),
 (2025, 278, 'ES1 0 CCGT', 0.0),
 (2025, 279, 'ES1 0 CCGT', 0.0),
 (2025, 280, 'ES1 0 CCGT', 0.0),
 (2025, 281, 'ES1 0 CCGT', 0.0),
 (2025, 282, 'ES1 0 CCGT', 0.0),
 (2025, 283, 'ES1 0 CCGT', 0.0),
 (2025, 284, 'ES1 0 CCGT', 0.0),
 (2025, 285, 'ES1 0 CCGT', 0.0),
 (2025, 286, 'ES1 0 CCGT', 0.0),
 (2025, 287, 'ES1 0 CCGT', 0.0),
 (2025, 288, 'ES1 0 CCGT', 0.0),
 (2025, 289, 'ES1 0 CCGT', 0.0),
 (2025, 290, 'ES1 0 CCGT', 0.0),
 (2025, 291, 'ES1 0 CCGT', 0.0),
 (2025, 292, 'ES1 0 CCGT', 0.0),
 (2025, 293, 'ES1 0 CCGT', 0.0),
 (2025, 294, 'ES1 0 CCGT', 0.0),
 (2025, 295, 'ES1 0 CCGT', 0.0),
 (2025, 296, 'ES1 0 CCGT', 0.0),
 (2025, 297, 'ES1 0 CCGT', 0.0),
 (2025, 298, 'ES1 0 CCGT', 0.0),
 (2025, 299, 'ES1 0 CCGT', 0.0),
 (2025, 300, 'ES1 0 CCGT', 0.0),
 (2025, 301, 'ES1 0 CCGT', 0.0),
 (2025, 302, 'ES1 0 CCGT', 0.0),
 (2025, 303, 'ES1 0 CCGT', 0.0),
 (2025, 304, 'ES1 0 CCGT', 0.0),
 (2025, 305, 'ES1 0 CCGT', 0.0),
 (2025, 306, 'ES1 0 CCGT', 0.0),
 (2025, 307, 'ES1 0 CCGT', 0.0),
 (2025, 308, 'ES1 0 CCGT', 0.0),
 (2025, 309, 'ES1 0 CCGT', 0.0),
 (2025, 310, 'ES1 0 CCGT', 0.0),
 (2025, 311, 'ES1 0 CCGT', 0.0),
 (2025, 312, 'ES1 0 CCGT', 0.0),
 (2025, 313, 'ES1 0 CCGT', 0.0),
 (2025, 314, 'ES1 0 CCGT', 0.0),
 (2025, 315, 'ES1 0 CCGT', 0.0),
 (2025, 316, 'ES1 0 CCGT', 0.0),
 (2025, 317, 'ES1 0 CCGT', 0.0),
 (2025, 318, 'ES1 0 CCGT', 0.0),
 (2025, 319, 'ES1 0 CCGT', 625.0138397272021),
 (2025, 320, 'ES1 0 CCGT', 776.3705132066889),
 (2025, 321, 'ES1 0 CCGT', 0.0),
 (2025, 322, 'ES1 0 CCGT', 0.0),
 (2025, 323, 'ES1 0 CCGT', 0.0),
 (2025, 324, 'ES1 0 CCGT', 0.0),
 (2025, 325, 'ES1 0 CCGT', 0.0),
 (2025, 326, 'ES1 0 CCGT', 0.0),
 (2025, 327, 'ES1 0 CCGT', 0.0),
 (2025, 328, 'ES1 0 CCGT', 0.0),
 (2025, 329, 'ES1 0 CCGT', 0.0),
 (2025, 330, 'ES1 0 CCGT', 683.8676128038796),
 (2025, 331, 'ES1 0 CCGT', 938.1552239828798),
 (2025, 332, 'ES1 0 CCGT', 386.580270931855),
 (2025, 333, 'ES1 0 CCGT', 0.0),
 (2025, 334, 'ES1 0 CCGT', 0.0),
 (2025, 335, 'ES1 0 CCGT', 0.0),
 (2025, 336, 'ES1 0 CCGT', 0.0),
 (2025, 337, 'ES1 0 CCGT', 0.0),
 (2025, 338, 'ES1 0 CCGT', 0.0),
 (2025, 339, 'ES1 0 CCGT', 0.0),
 (2025, 340, 'ES1 0 CCGT', 0.0),
 (2025, 341, 'ES1 0 CCGT', 0.0),
 (2025, 342, 'ES1 0 CCGT', 0.0),
 (2025, 343, 'ES1 0 CCGT', 0.0),
 (2025, 344, 'ES1 0 CCGT', 0.0),
 (2025, 345, 'ES1 0 CCGT', 0.0),
 (2025, 346, 'ES1 0 CCGT', 0.0),
 (2025, 347, 'ES1 0 CCGT', 0.0),
 (2025, 348, 'ES1 0 CCGT', 0.0),
 (2025, 349, 'ES1 0 CCGT', 0.0),
 (2025, 350, 'ES1 0 CCGT', 0.0),
 (2025, 351, 'ES1 0 CCGT', 0.0),
 (2025, 352, 'ES1 0 CCGT', 0.0),
 (2025, 353, 'ES1 0 CCGT', 0.0),
 (2025, 354, 'ES1 0 CCGT', 0.0),
 (2025, 355, 'ES1 0 CCGT', 0.0),
 (2025, 356, 'ES1 0 CCGT', 0.0),
 (2025, 357, 'ES1 0 CCGT', 0.0),
 (2025, 358, 'ES1 0 CCGT', 0.0),
 (2025, 359, 'ES1 0 CCGT', 0.0),
 (2025, 360, 'ES1 0 CCGT', 0.0),
 (2025, 361, 'ES1 0 CCGT', 0.0),
 (2025, 362, 'ES1 0 CCGT', 0.0),
 (2025, 363, 'ES1 0 CCGT', 0.0),
 (2025, 364, 'ES1 0 CCGT', 0.0),
 (2025, 365, 'ES1 0 CCGT', 0.0),
 (2025, 366, 'ES1 0 CCGT', 0.0),
 (2025, 367, 'ES1 0 CCGT', 0.0),
 (2025, 368, 'ES1 0 CCGT', 0.0),
 (2025, 369, 'ES1 0 CCGT', 0.0),
 (2025, 370, 'ES1 0 CCGT', 0.0),
 (2025, 371, 'ES1 0 CCGT', 0.0),
 (2025, 372, 'ES1 0 CCGT', 0.0),
 (2025, 373, 'ES1 0 CCGT', 0.0),
 (2025, 374, 'ES1 0 CCGT', 0.0),
 (2025, 375, 'ES1 0 CCGT', 0.0),
 (2025, 376, 'ES1 0 CCGT', 0.0),
 (2025, 377, 'ES1 0 CCGT', 0.0),
 (2025, 378, 'ES1 0 CCGT', 0.0),
 (2025, 379, 'ES1 0 CCGT', 0.0),
 (2025, 380, 'ES1 0 CCGT', 0.0),
 (2025, 381, 'ES1 0 CCGT', 0.0),
 (2025, 382, 'ES1 0 CCGT', 0.0),
 (2025, 383, 'ES1 0 CCGT', 0.0),
 (2025, 384, 'ES1 0 CCGT', 0.0),
 (2025, 385, 'ES1 0 CCGT', 0.0),
 (2025, 386, 'ES1 0 CCGT', 0.0),
 (2025, 387, 'ES1 0 CCGT', 0.0),
 (2025, 388, 'ES1 0 CCGT', 0.0),
 (2025, 389, 'ES1 0 CCGT', 0.0),
 (2025, 390, 'ES1 0 CCGT', 0.0),
 (2025, 391, 'ES1 0 CCGT', 0.0),
 (2025, 392, 'ES1 0 CCGT', 0.0),
 (2025, 393, 'ES1 0 CCGT', 0.0),
 (2025, 394, 'ES1 0 CCGT', 0.0),
 (2025, 395, 'ES1 0 CCGT', 0.0),
 (2025, 396, 'ES1 0 CCGT', 0.0),
 (2025, 397, 'ES1 0 CCGT', 0.0),
 (2025, 398, 'ES1 0 CCGT', 0.0),
 (2025, 399, 'ES1 0 CCGT', 0.0),
 (2025, 400, 'ES1 0 CCGT', 0.0),
 (2025, 401, 'ES1 0 CCGT', 0.0),
 (2025, 402, 'ES1 0 CCGT', 0.0),
 (2025, 403, 'ES1 0 CCGT', 0.0),
 (2025, 404, 'ES1 0 CCGT', 0.0),
 (2025, 405, 'ES1 0 CCGT', 0.0),
 (2025, 406, 'ES1 0 CCGT', 0.0),
 (2025, 407, 'ES1 0 CCGT', 0.0),
 (2025, 408, 'ES1 0 CCGT', 0.0),
 (2025, 409, 'ES1 0 CCGT', 0.0),
 (2025, 410, 'ES1 0 CCGT', 0.0),
 (2025, 411, 'ES1 0 CCGT', 0.0),
 (2025, 412, 'ES1 0 CCGT', 0.0),
 (2025, 413, 'ES1 0 CCGT', 0.0),
 (2025, 414, 'ES1 0 CCGT', 0.0),
 (2025, 415, 'ES1 0 CCGT', 0.0),
 (2025, 416, 'ES1 0 CCGT', 0.0),
 (2025, 417, 'ES1 0 CCGT', 0.0),
 (2025, 418, 'ES1 0 CCGT', 0.0),
 (2025, 419, 'ES1 0 CCGT', 0.0),
 (2025, 420, 'ES1 0 CCGT', 0.0),
 (2025, 421, 'ES1 0 CCGT', 0.0),
 (2025, 422, 'ES1 0 CCGT', 0.0),
 (2025, 423, 'ES1 0 CCGT', 0.0),
 (2025, 424, 'ES1 0 CCGT', 0.0),
 (2025, 425, 'ES1 0 CCGT', 0.0),
 (2025, 426, 'ES1 0 CCGT', 0.0),
 (2025, 427, 'ES1 0 CCGT', 0.0),
 (2025, 428, 'ES1 0 CCGT', 0.0),
 (2025, 429, 'ES1 0 CCGT', 0.0),
 (2025, 430, 'ES1 0 CCGT', 0.0),
 (2025, 431, 'ES1 0 CCGT', 0.0),
 (2025, 432, 'ES1 0 CCGT', 0.0),
 (2025, 433, 'ES1 0 CCGT', 0.0),
 (2025, 434, 'ES1 0 CCGT', 0.0),
 (2025, 435, 'ES1 0 CCGT', 0.0),
 (2025, 436, 'ES1 0 CCGT', 0.0),
 (2025, 437, 'ES1 0 CCGT', 0.0),
 (2025, 438, 'ES1 0 CCGT', 0.0),
 (2025, 439, 'ES1 0 CCGT', 0.0),
 (2025, 440, 'ES1 0 CCGT', 0.0),
 (2025, 441, 'ES1 0 CCGT', 0.0),
 (2025, 442, 'ES1 0 CCGT', 0.0),
 (2025, 443, 'ES1 0 CCGT', 0.0),
 (2025, 444, 'ES1 0 CCGT', 0.0),
 (2025, 445, 'ES1 0 CCGT', 0.0),
 (2025, 446, 'ES1 0 CCGT', 0.0),
 (2025, 447, 'ES1 0 CCGT', 0.0),
 (2025, 448, 'ES1 0 CCGT', 0.0),
 (2025, 449, 'ES1 0 CCGT', 0.0),
 (2025, 450, 'ES1 0 CCGT', 0.0),
 (2025, 451, 'ES1 0 CCGT', 0.0),
 (2025, 452, 'ES1 0 CCGT', 0.0),
 (2025, 453, 'ES1 0 CCGT', 0.0),
 (2025, 454, 'ES1 0 CCGT', 0.0),
 (2025, 455, 'ES1 0 CCGT', 0.0),
 (2025, 456, 'ES1 0 CCGT', 0.0),
 (2025, 457, 'ES1 0 CCGT', 0.0),
 (2025, 458, 'ES1 0 CCGT', 0.0),
 (2025, 459, 'ES1 0 CCGT', 0.0),
 (2025, 460, 'ES1 0 CCGT', 0.0),
 (2025, 461, 'ES1 0 CCGT', 0.0),
 (2025, 462, 'ES1 0 CCGT', 0.0),
 (2025, 463, 'ES1 0 CCGT', 0.0),
 (2025, 464, 'ES1 0 CCGT', 0.0),
 (2025, 465, 'ES1 0 CCGT', 0.0),
 (2025, 466, 'ES1 0 CCGT', 0.0),
 (2025, 467, 'ES1 0 CCGT', 0.0),
 (2025, 468, 'ES1 0 CCGT', 0.0),
 (2025, 469, 'ES1 0 CCGT', 0.0),
 (2025, 470, 'ES1 0 CCGT', 0.0),
 (2025, 471, 'ES1 0 CCGT', 0.0),
 (2025, 472, 'ES1 0 CCGT', 0.0),
 (2025, 473, 'ES1 0 CCGT', 0.0),
 (2025, 474, 'ES1 0 CCGT', 0.0),
 (2025, 475, 'ES1 0 CCGT', 0.0),
 (2025, 476, 'ES1 0 CCGT', 0.0),
 (2025, 477, 'ES1 0 CCGT', 0.0),
 (2025, 478, 'ES1 0 CCGT', 0.0),
 (2025, 479, 'ES1 0 CCGT', 0.0),
 (2025, 480, 'ES1 0 CCGT', 0.0),
 (2025, 481, 'ES1 0 CCGT', 0.0),
 (2025, 482, 'ES1 0 CCGT', 0.0),
 (2025, 483, 'ES1 0 CCGT', 0.0),
 (2025, 484, 'ES1 0 CCGT', 0.0),
 (2025, 485, 'ES1 0 CCGT', 0.0),
 (2025, 486, 'ES1 0 CCGT', 0.0),
 (2025, 487, 'ES1 0 CCGT', 0.0),
 (2025, 488, 'ES1 0 CCGT', 0.0),
 (2025, 489, 'ES1 0 CCGT', 0.0),
 (2025, 490, 'ES1 0 CCGT', 0.0),
 (2025, 491, 'ES1 0 CCGT', 0.0),
 (2025, 492, 'ES1 0 CCGT', 0.0),
 (2025, 493, 'ES1 0 CCGT', 0.0),
 (2025, 494, 'ES1 0 CCGT', 0.0),
 (2025, 495, 'ES1 0 CCGT', 0.0),
 (2025, 496, 'ES1 0 CCGT', 0.0),
 (2025, 497, 'ES1 0 CCGT', 0.0),
 (2025, 498, 'ES1 0 CCGT', 2418.6482627320347),
 (2025, 499, 'ES1 0 CCGT', 3396.632662637483),
 (2025, 500, 'ES1 0 CCGT', 3006.217742011808),
 (2025, 501, 'ES1 0 CCGT', 0.0),
 (2025, 502, 'ES1 0 CCGT', 0.0),
 (2025, 503, 'ES1 0 CCGT', 0.0),
 (2025, 504, 'ES1 0 CCGT', 0.0),
 (2025, 505, 'ES1 0 CCGT', 0.0),
 (2025, 506, 'ES1 0 CCGT', 0.0),
 (2025, 507, 'ES1 0 CCGT', 0.0),
 (2025, 508, 'ES1 0 CCGT', 0.0),
 (2025, 509, 'ES1 0 CCGT', 0.0),
 (2025, 510, 'ES1 0 CCGT', 0.0),
 (2025, 511, 'ES1 0 CCGT', 0.0),
 (2025, 512, 'ES1 0 CCGT', 0.0),
 (2025, 513, 'ES1 0 CCGT', 0.0),
 (2025, 514, 'ES1 0 CCGT', 0.0),
 (2025, 515, 'ES1 0 CCGT', 0.0),
 (2025, 516, 'ES1 0 CCGT', 0.0),
 (2025, 517, 'ES1 0 CCGT', 0.0),
 (2025, 518, 'ES1 0 CCGT', 0.0),
 (2025, 519, 'ES1 0 CCGT', 0.0),
 (2025, 520, 'ES1 0 CCGT', 0.0),

In [ ]:
generation_df = pd.DataFrame(
    generation_data, columns=["year", "hour", "generator", "value"]
)
print(generation_df)

        year  hour        generator  value
0       2025     0       ES1 0 CCGT    0.0
1       2025     1       ES1 0 CCGT    0.0
2       2025     2       ES1 0 CCGT    0.0
3       2025     3       ES1 0 CCGT    0.0
4       2025     4       ES1 0 CCGT    0.0
...      ...   ...              ...    ...
578155  2045  8755  PT1 0 solar new    0.0
578156  2045  8756  PT1 0 solar new    0.0
578157  2045  8757  PT1 0 solar new    0.0
578158  2045  8758  PT1 0 solar new    0.0
578159  2045  8759  PT1 0 solar new    0.0

[578160 rows x 4 columns]

In [ ]:
# Helper function to reshape a variable with time and other indices
def _reshape_multi(data, index, column_name, value_name):
    """Reshape the data to have time as rows and other index (e.g., generator) as columns."""
    reshaped = data.reset_index().pivot(
        index=index, columns=column_name, values=value_name
    )
    reshaped.columns.name = None  # Remove the name of the columns for cleaner output
    return reshaped