## First notebook for getting required data for the master thesis formulations of the problem.

- Demand data (Spain and Portugal)
- Renewable energy potential
- Generators investment costs
- Generators production costs
- CO₂ price
- Battery investment costs
- Battery production/O&M costs
- Transmission line investment costs
- Transmission line capacity now
- Transmission line potential?
- Renewable energy curves?
  - solar
  - wind offshore
  - wind onshore
  - ror
- Suitable discount rates for entire model
- Suitable discount rates for assets (to calculate AIC)
- VOLL
- Curtailment cost
- Battery technical data
- Scenario data (high, medium, low demand)

In [1]:
import sys
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Determine the absolute path to the src directory (one level up from notebooks)
module_path = os.path.abspath(os.path.join("..", "src"))
if module_path not in sys.path:
    sys.path.append(module_path)

import plotting
import utils

In [2]:
data_path = os.path.join(os.path.dirname(os.getcwd()), "data")
exploration_path = os.path.join(data_path, "exploration")
entsoe_path = os.path.join(exploration_path, "entsoe")

In [3]:
load_2025_ES_weekly = pd.read_csv(
    os.path.join(entsoe_path, "Total Load Forecast - Year Ahead 2024 pred 2025 ES.csv"),
    index_col=0,
)
load_2025_PT_weekly = pd.read_csv(
    os.path.join(entsoe_path, "Total Load Forecast - Year Ahead 2024 pred 2025 PT.csv"),
    index_col=0,
)
load_2025_PT_weekly

         Min Total Load [MW] - BZN|PT  Max Total Load [MW] - BZN|PT
Week
Week 2                           3659                          9337
Week 3                           3967                          9522
Week 4                           3942                          9385
Week 5                           4186                          9643
Week 6                           4052                          9170
Week 7                           4000                          8983
Week 8                           4051                          8941
Week 9                           4095                          8737
Week 10                          4049                          8570
Week 11                          3902                          8388
Week 12                          3794                          8450
Week 13                          3805                          8053
Week 13                          3780                          7740
Week 14                          3736                          7900
Week 15                          3695                          7572
Week 16                          3430                          7467
Week 17                          3313                          7155
Week 18                          3439                          7151
Week 19                          3439                          7364
Week 20                          3421                          7262
Week 21                          3425                          7188
Week 22                          3476                          7215
Week 23                          3504                          7186
Week 24                          3615                          7375
Week 25                          3648                          7351
Week 26                          3699                          7335
Week 27                          3798                          7455
Week 28                          3828                          7619
Week 29                          3892                          7632
Week 30                          3987                          7563
Week 31                          3886                          7683
Week 32                          3937                          7241
Week 33                          3827                          7083
Week 34                          3809                          6782
Week 35                          3755                          6853
Week 36                          3843                          7386
Week 37                          3810                          7386
Week 38                          3738                          7417
Week 39                          3707                          7311
Week 40                          3530                          7317
Week 41                          3783                          7447
Week 42                          3710                          7495
Week 44                          3771                          7664
Week 45                          3099                          7832
Week 46                          3697                          8088
Week 47                          3822                          8343
Week 48                          3882                          8619
Week 49                          3976                          8980
Week 50                          4160                          9474
Week 51                          4150                          9393
Week 52                          4166                          9338
Week 1                           3675                          9019

In [4]:
load_2025 = pd.merge(
    load_2025_ES_weekly, load_2025_PT_weekly, left_index=True, right_index=True
)
load_2025

,Min Total Load [MW] - BZN|ES,Max Total Load [MW] - BZN|ES,Min Total Load [MW] - BZN|PT,Max Total Load [MW] - BZN|PT
Week,,,,
Week 1,17979,34586,3675,9019
Week 2,19702,38675,3659,9337
Week 3,21818,38865,3967,9522
Week 4,21731,38832,3942,9385
Week 5,21761,38318,4186,9643
Week 6,21724,37660,4052,9170
Week 7,21488,37587,4000,8983
Week 8,21405,37220,4051,8941
Week 9,21183,36525,4095,8737
Week 10,21124,36591,4049,8570
Week 11,20119,36052,3902,8388
Week 12,20312,34949,3794,8450
Week 13,19091,34419,3805,8053
Week 13,19091,34419,3780,7740
Week 14,18722,33310,3736,7900
Week 15,18432,33467,3695,7572
Week 16,16138,31423,3430,7467
Week 17,18090,31940,3313,7155
Week 18,17226,31645,3439,7151
Week 19,17284,31179,3439,7364
Week 20,17309,31306,3421,7262
Week 21,17484,30756,3425,7188
Week 22,17484,30589,3476,7215
Week 23,17332,31061,3504,7186
Week 24,17917,31329,3615,7375
Week 25,18224,31143,3648,7351
Week 26,18406,32400,3699,7335
Week 27,18933,32800,3798,7455
Week 28,19054,33890,3828,7619
Week 29,19387,34177,3892,7632
Week 30,19359,34059,3987,7563
Week 31,19286,33650,3886,7683
Week 32,19058,32978,3937,7241
Week 33,19396,32475,3827,7083
Week 34,18889,33440,3809,6782
Week 35,19209,33759,3755,6853
Week 36,19226,33660,3843,7386
Week 37,19165,33760,3810,7386
Week 38,19021,33020,3738,7417
Week 39,18872,32790,3707,7311
Week 40,19158,33051,3530,7317
Week 41,19690,33033,3783,7447
Week 42,19158,33096,3710,7495
Week 44,19637,33286,3771,7664
Week 45,19579,34118,3099,7832
Week 46,20103,34764,3697,8088
Week 47,20232,35714,3822,8343
Week 48,20857,36605,3882,8619
Week 49,21492,37922,3976,8980
Week 50,21349,38005,4160,9474
Week 51,21352,37794,4150,9393
Week 52,18909,37523,4166,9338

In [5]:
load_2025.sum(axis=0)
load_2025.columns

Index(['Min Total Load [MW] - BZN|ES', 'Max Total Load [MW] - BZN|ES',
       'Min Total Load [MW] - BZN|PT', 'Max Total Load [MW] - BZN|PT'],
      dtype='object')

In [6]:
load_2025["Min combined"] = (
    load_2025.loc[:, "Min Total Load [MW] - BZN|ES"]
    + load_2025.loc[:, "Min Total Load [MW] - BZN|PT"]
)
load_2025["Max combined"] = (
    load_2025.loc[:, "Max Total Load [MW] - BZN|ES"]
    + load_2025.loc[:, "Max Total Load [MW] - BZN|PT"]
)
load_2025.sum(axis=0) * 24 * 7 / 1e6

Min Total Load [MW] - BZN|ES    169.503096
Max Total Load [MW] - BZN|ES    299.983320
Min Total Load [MW] - BZN|PT     32.988480
Max Total Load [MW] - BZN|PT     69.696480
Min combined                    202.491576
Max combined                    369.679800
dtype: float64

In [7]:
hourly_demand = pd.read_csv(
    os.path.join(data_path, "processed", "elec_s_37_ES_PT", "hourly_demand.csv"),
    index_col=0,
)
hourly_demand.sum(axis=0) / 1e6

ES1 0    241.174022
PT1 0     49.104255
dtype: float64

In [8]:
hourly_demand.sum().sum() / 1e6

290.27827617288455

In [9]:
(202 + 369) / 2

285.5

In [16]:
test_path = r"C:\Users\tinus\OneDrive\Dokumenter\0 Master\code\master_project\data\exploration\bundle\je-e-21.03.02.xls"

In [18]:
df = pd.read_csv(test_path)
df

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd0 in position 0: invalid continuation byte